BannerPageBlock:
    type: object
    inherits:
        - BasePageBlock
    config:
        fields:
            contentId:
                type: Item
                resolve: '@=resolver("EmbedAttributeValue", [value.getAttribute("contentId").getValue()])'
            url:
                type: String
                resolve: '@=value.getAttribute("url").getValue()'
