ContentTypeIdentifier:
    type: enum
    config:
        values:
            bike_ride:
                description: 'No description available'
            point_of_interest:
                description: 'No description available'
            product_page:
                description: 'A simple product page'
            article:
                description: 'No description available'
            folder:
                description: 'No description available'
            form:
                description: 'No description available'
            tag:
                description: 'No description available'
            landing_page: {  }
            product_category_tag:
                description: 'No description available'
            user:
                description: 'No description available'
            user_group:
                description: 'No description available'
            file:
                description: 'No description available'
            image:
                description: 'No description available'
