FormPageBlockViews:
    type: enum
    config:
        values:
            default:
                value: '@IbexaFormBuilder/blocks/form.html.twig'
                description: 'Default block layout'
