FormItemConnection:
    type: relay-connection
    config:
        nodeType: FormItem
        connectionFields:
            sliceSize:
                type: Int!
            orderBy:
                type: String
