ItemGroupContent:
    type: object
    inherits:
        - DomainContentTypeGroup
    config:
        fields:
            _types:
                type: ItemGroupContentTypes
                resolve: {  }
            bikeRides:
                type: BikeRideItemConnection
                description: 'No description available'
                resolve: '@=resolver("ItemsOfTypeAsConnection", ["bike_ride", args])'
                argsBuilder: 'Relay::Connection'
                args:
                    query: { type: ContentSearchQuery, description: 'A Content query used to filter results' }
                    sortBy: { type: '[SortByOptions]', description: 'A Sort Clause, or array of Clauses. Add _desc after a Clause to reverse it' }
            bikeRide:
                type: BikeRideItem
                description: 'No description available'
                resolve: '@=resolver("ItemOfType", [args, "bike_ride"])'
                args:
                    contentId: { type: Int, description: 'Content ID of the bike_ride' }
                    remoteId: { type: String, description: 'Content remote ID of the bike_ride' }
                    locationId: { type: Int, description: 'Location ID of the bike_ride' }
                    locationRemoteId: { type: String, description: 'Location remote ID of the bike_ride' }
                    urlAlias: { type: String, description: 'URL alias of the bike_ride' }
            pointOfInterests:
                type: PointOfInterestItemConnection
                description: 'No description available'
                resolve: '@=resolver("ItemsOfTypeAsConnection", ["point_of_interest", args])'
                argsBuilder: 'Relay::Connection'
                args:
                    query: { type: ContentSearchQuery, description: 'A Content query used to filter results' }
                    sortBy: { type: '[SortByOptions]', description: 'A Sort Clause, or array of Clauses. Add _desc after a Clause to reverse it' }
            pointOfInterest:
                type: PointOfInterestItem
                description: 'No description available'
                resolve: '@=resolver("ItemOfType", [args, "point_of_interest"])'
                args:
                    contentId: { type: Int, description: 'Content ID of the point_of_interest' }
                    remoteId: { type: String, description: 'Content remote ID of the point_of_interest' }
                    locationId: { type: Int, description: 'Location ID of the point_of_interest' }
                    locationRemoteId: { type: String, description: 'Location remote ID of the point_of_interest' }
                    urlAlias: { type: String, description: 'URL alias of the point_of_interest' }
            productPages:
                type: ProductPageItemConnection
                description: 'A simple product page'
                resolve: '@=resolver("ItemsOfTypeAsConnection", ["product_page", args])'
                argsBuilder: 'Relay::Connection'
                args:
                    query: { type: ContentSearchQuery, description: 'A Content query used to filter results' }
                    sortBy: { type: '[SortByOptions]', description: 'A Sort Clause, or array of Clauses. Add _desc after a Clause to reverse it' }
            productPage:
                type: ProductPageItem
                description: 'A simple product page'
                resolve: '@=resolver("ItemOfType", [args, "product_page"])'
                args:
                    contentId: { type: Int, description: 'Content ID of the product_page' }
                    remoteId: { type: String, description: 'Content remote ID of the product_page' }
                    locationId: { type: Int, description: 'Location ID of the product_page' }
                    locationRemoteId: { type: String, description: 'Location remote ID of the product_page' }
                    urlAlias: { type: String, description: 'URL alias of the product_page' }
            articles:
                type: ArticleItemConnection
                description: 'No description available'
                resolve: '@=resolver("ItemsOfTypeAsConnection", ["article", args])'
                argsBuilder: 'Relay::Connection'
                args:
                    query: { type: ContentSearchQuery, description: 'A Content query used to filter results' }
                    sortBy: { type: '[SortByOptions]', description: 'A Sort Clause, or array of Clauses. Add _desc after a Clause to reverse it' }
            article:
                type: ArticleItem
                description: 'No description available'
                resolve: '@=resolver("ItemOfType", [args, "article"])'
                args:
                    contentId: { type: Int, description: 'Content ID of the article' }
                    remoteId: { type: String, description: 'Content remote ID of the article' }
                    locationId: { type: Int, description: 'Location ID of the article' }
                    locationRemoteId: { type: String, description: 'Location remote ID of the article' }
                    urlAlias: { type: String, description: 'URL alias of the article' }
            folders:
                type: FolderItemConnection
                description: 'No description available'
                resolve: '@=resolver("ItemsOfTypeAsConnection", ["folder", args])'
                argsBuilder: 'Relay::Connection'
                args:
                    query: { type: ContentSearchQuery, description: 'A Content query used to filter results' }
                    sortBy: { type: '[SortByOptions]', description: 'A Sort Clause, or array of Clauses. Add _desc after a Clause to reverse it' }
            folder:
                type: FolderItem
                description: 'No description available'
                resolve: '@=resolver("ItemOfType", [args, "folder"])'
                args:
                    contentId: { type: Int, description: 'Content ID of the folder' }
                    remoteId: { type: String, description: 'Content remote ID of the folder' }
                    locationId: { type: Int, description: 'Location ID of the folder' }
                    locationRemoteId: { type: String, description: 'Location remote ID of the folder' }
                    urlAlias: { type: String, description: 'URL alias of the folder' }
            forms:
                type: FormItemConnection
                description: 'No description available'
                resolve: '@=resolver("ItemsOfTypeAsConnection", ["form", args])'
                argsBuilder: 'Relay::Connection'
                args:
                    query: { type: ContentSearchQuery, description: 'A Content query used to filter results' }
                    sortBy: { type: '[SortByOptions]', description: 'A Sort Clause, or array of Clauses. Add _desc after a Clause to reverse it' }
            form:
                type: FormItem
                description: 'No description available'
                resolve: '@=resolver("ItemOfType", [args, "form"])'
                args:
                    contentId: { type: Int, description: 'Content ID of the form' }
                    remoteId: { type: String, description: 'Content remote ID of the form' }
                    locationId: { type: Int, description: 'Location ID of the form' }
                    locationRemoteId: { type: String, description: 'Location remote ID of the form' }
                    urlAlias: { type: String, description: 'URL alias of the form' }
            tags:
                type: TagItemConnection
                description: 'No description available'
                resolve: '@=resolver("ItemsOfTypeAsConnection", ["tag", args])'
                argsBuilder: 'Relay::Connection'
                args:
                    query: { type: ContentSearchQuery, description: 'A Content query used to filter results' }
                    sortBy: { type: '[SortByOptions]', description: 'A Sort Clause, or array of Clauses. Add _desc after a Clause to reverse it' }
            tag:
                type: TagItem
                description: 'No description available'
                resolve: '@=resolver("ItemOfType", [args, "tag"])'
                args:
                    contentId: { type: Int, description: 'Content ID of the tag' }
                    remoteId: { type: String, description: 'Content remote ID of the tag' }
                    locationId: { type: Int, description: 'Location ID of the tag' }
                    locationRemoteId: { type: String, description: 'Location remote ID of the tag' }
                    urlAlias: { type: String, description: 'URL alias of the tag' }
            landingPages:
                type: LandingPageItemConnection
                resolve: '@=resolver("ItemsOfTypeAsConnection", ["landing_page", args])'
                argsBuilder: 'Relay::Connection'
                args:
                    query: { type: ContentSearchQuery, description: 'A Content query used to filter results' }
                    sortBy: { type: '[SortByOptions]', description: 'A Sort Clause, or array of Clauses. Add _desc after a Clause to reverse it' }
            landingPage:
                type: LandingPageItem
                resolve: '@=resolver("ItemOfType", [args, "landing_page"])'
                args:
                    contentId: { type: Int, description: 'Content ID of the landing_page' }
                    remoteId: { type: String, description: 'Content remote ID of the landing_page' }
                    locationId: { type: Int, description: 'Location ID of the landing_page' }
                    locationRemoteId: { type: String, description: 'Location remote ID of the landing_page' }
                    urlAlias: { type: String, description: 'URL alias of the landing_page' }
            productCategoryTags:
                type: ProductCategoryTagItemConnection
                description: 'No description available'
                resolve: '@=resolver("ItemsOfTypeAsConnection", ["product_category_tag", args])'
                argsBuilder: 'Relay::Connection'
                args:
                    query: { type: ContentSearchQuery, description: 'A Content query used to filter results' }
                    sortBy: { type: '[SortByOptions]', description: 'A Sort Clause, or array of Clauses. Add _desc after a Clause to reverse it' }
            productCategoryTag:
                type: ProductCategoryTagItem
                description: 'No description available'
                resolve: '@=resolver("ItemOfType", [args, "product_category_tag"])'
                args:
                    contentId: { type: Int, description: 'Content ID of the product_category_tag' }
                    remoteId: { type: String, description: 'Content remote ID of the product_category_tag' }
                    locationId: { type: Int, description: 'Location ID of the product_category_tag' }
                    locationRemoteId: { type: String, description: 'Location remote ID of the product_category_tag' }
                    urlAlias: { type: String, description: 'URL alias of the product_category_tag' }
