LandingPageItemUpdateInput:
    type: input-object
    config:
        fields:
            name:
                type: String
                description: Title
            description:
                type: String
                description: 'Landing page description'
            page:
                type: String
                description: 'Landing page'
