PersonalizedPageBlockViews:
    type: enum
    config:
        values:
            default:
                value: '@IbexaPersonalization/blocks/personalized.html.twig'
                description: 'Default block layout'
